"""Added role to Users

Revision ID: 73411fce37f9
Revises: 539a4830c7a4
Create Date: 2024-05-16 13:11:11.543921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73411fce37f9'
down_revision = '539a4830c7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
